### ISSUE TITLE
Running selenium with PhantomJS

### ISSUE THREAD

**Issue by YuanZheCSYZ** [detro/ghostdriver#483] opened 2016-08-25 06:08 UTC
Hi,

I'm trying to run my Python Selenium testing with PhantomJS but I came across several issues.
I'm running Ubuntu 16.04 with Python 3.5.2, Selenium 2.47.1 and PhantomJS 2.1.1.

The first test is very basic, but this is how I used to use I think

``` python
from selenium import webdriver
driver = webdriver.PhantomJS()
```

And I receive below stacktrace

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    driver = webdriver.PhantomJS()
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 136, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Then I tried to using it with Selenium server standalone (3.0.0-beta2)
`java -jar ./selenium-server-standalone-3.0.0-beta2.jar -role hub`

```
15:23:35.356 INFO - Selenium build info: version: '3.0.0-beta2', revision: '2aa21c1'
15:23:35.357 INFO - Launching Selenium Grid hub
2016-08-25 15:23:35.814:INFO::main: Logging initialized @714ms
15:23:35.827 INFO - Will listen on 4444
2016-08-25 15:23:35.871:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2016-08-25 15:23:35.902:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@4ba2ca36{/,null,AVAILABLE}
2016-08-25 15:23:35.912:INFO:osjs.ServerConnector:main: Started ServerConnector@6385cb26{HTTP/1.1}{0.0.0.0:4444}
2016-08-25 15:23:35.913:INFO:osjs.Server:main: Started @812ms
15:23:35.914 INFO - Nodes should register to http://192.168.122.1:4444/grid/register/
15:23:35.914 INFO - Selenium Grid hub is up and running
```

And running PhantomJS against the hub
`./phantomjs --webdriver=8003 --webdriver-selenium-grid-hub=http://localhost:4444`

```
[INFO  - 2016-08-25T05:55:03.054Z] GhostDriver - Main - running on port 8888
[INFO  - 2016-08-25T05:55:03.055Z] GhostDriver - Main - registering to Selenium HUB 'http://localhost:4444' version:  using '127.0.0.1:8888' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2016-08-25T05:55:03.057Z] GhostDriver - main.fail - {"line":97,"sourceURL":"phantomjs://platform/hub_register.js","stack":"register@phantomjs://platform/hub_register.js:97:79\nglobal code@phantomjs://code/main.js:78:37"}

  phantomjs://platform/console++.js:263 in error
```

Any help is much appreciate!

**Comment by uxnow** [comment] 2016-08-31 05:50
+1

**Comment by isian14** [comment] 2016-08-31 16:36
+1

**Comment by jesg** [comment] 2016-09-12 15:54
@YuanZheCSYZ i was able to reproduce the error when executing `phantomjs --webdriver=8003 --webdriver-selenium-grid-hub=http://localhost:4444` if i already had phantomjs running at 8003.  you can only run one phantomjs instance per port.

i was unable to reproduce the other issue on python 3 and selenium 2.53.6.

**Comment by YuanZheCSYZ** [comment] 2016-09-13 03:37
@jesg Thanks for your effort. I am quite sure I have only one PhantomJS running then.

**Comment by RossTsachev** [comment] 2016-10-07 13:00
I get the same error on Ubuntu 14.04 Selenium 2.53.1 and PhantomJS 2.1.1

**Comment by InkUisitor** [comment] 2016-10-21 13:40
To avoid the problem when you want to use SeleniumGrid you can comment the line

`//platform: ghostdriver.system.os.name + '-' + ghostdriver.system.os.version + '-' + ghostdriver.system.os.architecture`

in the file hub_register.js
Recompile a new custom PhantomJS and when you will use `phantomjs --webdriver=8003 --webdriver-selenium-grid-hub=http://localhost:4444` this will work.
Enjoy the other problems you will encounter later (ssl params...)

**Comment by jesg** [comment] 2016-10-21 13:45
@YuanZheCSYZ i can reproduce it now.  not sure why i was not able to before.

 on phantomjs 2.1.1 i get the following error:
```
phantomjs --webdriver=8003 --webdriver-selenium-grid-hub=http://127.0.0.1:4444/wd/hub
[INFO  - 2016-10-21T12:35:53.696Z] GhostDriver - Main - running on port 8003
[INFO  - 2016-10-21T12:35:53.696Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4444/wd/hub' version:  using '127.0.0.1:8003' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2016-10-21T12:35:53.698Z] GhostDriver - main.fail - {"line":97,"sourceURL":"phantomjs://platform/hub_register.js","stack":"register@phantomjs://platform/hub_register.js:97:79\nglobal code@phantomjs://code/main.js:78:37"}

  phantomjs://platform/console++.js:263 in error
```

i get the following on ghostdriver's master branch:
```
$ phantomjs /home/jesg/opensource/ghostdriver/src/main.js --hub=http://127.0.0.1:4444/wd/hub --ip=127.0.0.1 --port=8003
[INFO  - 2016-10-21T12:38:17.727Z] GhostDriver - Main - running on port 127.0.0.1:8003
[INFO  - 2016-10-21T12:38:17.728Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4444/wd/hub' version:  using '127.0.0.1:8003' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2016-10-21T12:38:17.763Z] HUB Register - register - Problem registering with grid http://127.0.0.1:4444/wd/hub/: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"state":"unhandled error","sessionId":null,"hCode":1184652500,"value":{"additionalInformation":"\nDriver info: driver.version: unknown","localizedMessage":"POST /grid/register\nBuild info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'\nSystem info: host: 'jesg', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-38-generic', java.version: '1.8.0_91'\nDriver info: driver.version: unknown","supportUrl":null,"systemInformation":"System info: host: 'jesg', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-38-generic', java.version: '1.8.0_91'","cause":null,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"suppressed":[],"message":"POST /grid/register\nBuild info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'\nSystem info: host: 'jesg', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-38-generic', java.version: '1.8.0_91'\nDriver info: driver.version: unknown","hCode":389622459,"class":"org.openqa.selenium.UnsupportedCommandException","buildInformation":null},"class":"org.openqa.selenium.remote.Response","status":13}</pre></body></html>

  phantomjs://platform/console++.js:263 in error
```

something in selenium server is throwing an error.
```
java/client/src/org/openqa/selenium/WebDriverException.java
30:  public static final String DRIVER_INFO = "Driver info";
110:    if (! extraInfo.containsKey(DRIVER_INFO)) {
111:      extraInfo.put(DRIVER_INFO, "driver.version: " + getDriverName(getStackTrace()));
```

**Comment by jesg** [comment] 2017-03-23 02:25
should be fixed in 2.0.0

**Closed by jesg** 2017-03-23 02:25 UTC

**Comment by sherlock1982** [comment] 2017-06-16 20:40
Can still reproduce with 2.1.1 and latest selenium grid:

norekhov@debian:/lib/systemd/system$ sudo /usr/local/bin/phantomjs --webdriver=234 --webdriver-selenium-grid-hub=http://localhost:4444
[INFO  - 2017-06-16T20:34:32.433Z] GhostDriver - Main - running on port 234
[INFO  - 2017-06-16T20:34:32.433Z] GhostDriver - Main - registering to Selenium HUB 'http://localhost:4444' version:  using '127.0.0.1:234' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2017-06-16T20:34:32.439Z] GhostDriver - main.fail - {"line":97,"sourceURL":"phantomjs://platform/hub_register.js","stack":"register@phantomjs://platform/hub_register.js:97:79\nglobal code@phantomjs://code/main.js:78:37"}

**Comment by jesg** [comment] 2017-06-17 11:40
@sherlock1982 you need to upgrade to ghostdriver `2.0.0`.

**Comment by sherlock1982** [comment] 2017-06-17 15:33
Sorry, could you please explain. PhantomJS 2.1.1 is the latest released. 
What version does it include? 
So there are no binaries and I need to build it for myself with proper version of Ghostdriver?

**Comment by jesg** [comment] 2017-06-18 12:36
> What version does it include?

it includes ghostdriver 1.2.0 (2af7099a9).

> So there are no binaries

yes there are no binaries.

> and I need to build it for myself with proper version of Ghostdriver?

not necessarily.  you can run it with a bash [script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh), or npm [package](https://www.npmjs.com/package/ghostdriver).  since you are working with selenium grid you can also set it up with the java system property `phantomjs.ghostdriver.path`.  where `phantomjs.ghostdriver.path` points to `src/main.js` in this repository.

if you decide to build from source you should use https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1 and follow the instructions at https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1/deploy.

**Comment by iShreesh** [comment] 2017-07-05 14:21
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setJavascriptEnabled(true);
        capabilities.setCapability("takeScreenshot", true);
        capabilities.setCapability("phantomjs.page.settings.loadImages", false);
        System.setProperty(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
                TestConstants.getPhantomjsBinaryPath());
        WebDriver driver = new PhantomJSDriver(capabilities);

I m getting error while running Selenium Webdriver Java code.

"[ERROR - 2017-07-05T14:07:36.588Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1499263656562

  phantomjs://platform/console++.js:263 in error"

**Comment by lawred2** [comment] 2017-09-27 17:36
Why was this closed? Was it resolved?

**Comment by bappr** [comment] 2018-01-16 03:08
Still facing the same issue.
Not resolved.
Using 2.1.1

**Comment by MattyShires** [comment] 2018-03-27 16:16
Same issue on PhantomJS 2.1.1 and Selenium 3.11:

`[test@gemini]$ phantomjs --webdriver=localhost:4445 --webdriver-selenium-grid-hub=http://localhost:4444`
`[INFO  - 2018-03-27T15:58:47.294Z] GhostDriver - Main - running on port 4445`
`[INFO  - 2018-03-27T15:58:47.294Z] GhostDriver - Main - registering to Selenium HUB 'http://localhost:4444' version:  using 'localhost:4445' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.`
`[ERROR - 2018-03-27T15:58:47.298Z] GhostDriver - main.fail - {"line":97,"sourceURL":"phantomjs://platform/hub_register.js","stack":"register@phantomjs://platform/hub_register.js:97:79\nglobal code@phantomjs://code/main.js:78:37"}`
`  phantomjs://platform/console++.js:263 in error`

By using curl I can confirm that Selenium is in fact listening on port 4444 and is responding.

**Comment by bochen2014** [comment] 2018-05-14 15:10
given that I have zero java development experience, can @jesg  elaberate on 
> not necessarily. you can run it with a bash script, or npm package. since you are working with selenium grid you can also set it up with the java system property phantomjs.ghostdriver.path. where phantomjs.ghostdriver.path points to src/main.js in this repository.

I have already got `phantomjs-prebuilt` installed via `npm`, and it has `ghost-drive@1.2.0` shipped which needs to be upgraded.  How do we upgrade?  can you give detailed instructions?

As I said I don't have java dev experience and I don't use maven. Does that mean we can't use java binding? ( I can confirm that java binding doesn't work with latest selenium 3.12

**Comment by kelvinau** [comment] 2018-09-12 04:50
it seems to be a memory issue to me for selenium using phantomjs. It solves the issue after I add `--disk-cache=true`
