### ISSUE TITLE
FileUploadTest unit test hangs with Phantomjs 2.0

### ISSUE THREAD

**Issue by sureshvv** [detro/ghostdriver#447] opened 2015-04-17 08:30 UTC
Linux box running ubuntu 14.04

**Comment by sureshvv** [comment] 2015-04-17 17:04
https://github.com/ariya/phantomjs/issues/12506 patch fixes this

**Comment by asolntsev** [comment] 2016-04-23 10:08
@sureshvv I think it's a duplicate of [issue 282](https://github.com/detro/ghostdriver/issues/282): "PhantomJS hanging on file upload (multiple)"

**Comment by jesg** [comment] 2017-03-23 02:16
fixed in 2.0.0 release

**Closed by jesg** 2017-03-23 02:16 UTC

**Comment by asolntsev** [comment] 2017-06-01 17:56
@jesg When do you plan to release version 2.0.0?

**Comment by jesg** [comment] 2017-06-02 12:14
@asolntsev 
> When do you plan to release version 2.0.0?

it has been [released](https://github.com/detro/ghostdriver/releases/tag/2.0.0).  published on [npm](https://www.npmjs.com/package/ghostdriver) and [jitpack](https://jitpack.io/#detro/ghostdriver).  it has not been merged upstream into phantomjs.

are you looking for something else?

**Comment by asolntsev** [comment] 2017-06-02 12:20
@jesg Hm.. I am not sure... Actually I just need to incorporate the new version into https://github.com/detro/ghostdriver/ to fix the initial problem with hanging FileUploadTest.

**Comment by jesg** [comment] 2017-06-02 15:39
> initial problem with hanging FileUploadTest

this issue is fixed in https://github.com/detro/ghostdriver.  if it is not fixed please provide a detailed example that i can use to reproduce the issue.

not sure i'm following the phrase "incorporate the new version".   is there a need for a new version?

what do you want to merge into [detro/ghostdriver](https://github.com/detro/ghostdriver)?  what is the motivation for the change?
